Test record service
fogbow/accounting-service pull request #3
Opened 2019-07-31 19:19 UTC by raonismaneoto

2019-08-01 11:22 UTC, wassoares commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +            recordService.checkInterval(startTimeStamp, endTimeStamp);
Use 'Assert.fail()' after line 48 to evidence that the test must fail on this 'try/catch' line.

2019-08-01 11:25 UTC, wassoares commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +            recordService.checkInterval(startTimestamp, endTimestamp);
Use the same correction described in the previous comment.

2019-08-01 11:33 UTC, wassoares commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +        List<Record> records = recordService.getOpenedRecords(getAccountingUser(),"mockedRequestingMember", DEFAULT_RESOURCE_TYPE,
Transform the string "mockedRequestingMember" into a constant of this class and use it between test methods.

2019-08-01 12:01 UTC, wassoares commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +@PowerMockIgnore({"javax.management.*"})
Try to describe what the annotation on this line does to make it clear why it is being used in the test.

2019-08-01 12:05 UTC, wassoares commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +@SpringBootTest
It would no longer be appropriate to use these test configuration annotations in the ServicesBaseUnitTest class.

2019-08-01 12:36 UTC, wassoares requested changes
Thanks, @raonismaneoto... Good job! I only request some minor modifications to accept your PR.

2019-08-06 21:07 UTC, ANKerD requested changes

2019-08-06 21:07 UTC, ANKerD commented on src/test/java/cloud/fogbow/accs/core/datastore/services/RecordServiceTest.java
> +        mockDatabaseOperations(RECORDS_BY_USER, null, SELF, null, 2);
Extract these magic primitive values into constants.

2019-08-07 18:38 UTC, wassoares approved these changes

2019-08-07 18:42 UTC, merged