Application facade test
fogbow/accounting-service pull request #6
Opened 2019-08-08 12:33 UTC by raonismaneoto

2019-08-08 14:08 UTC, ANKerD requested changes
It's missing test case descriptions and setup/exercise/verify comments on ApplicationFacadeTest.

2019-08-08 14:08 UTC, ANKerD commented on src/test/java/cloud/fogbow/accs/core/ApplicationFacadeTest.java
> +    ApplicationFacade applicationFacade;
Add the appropriate access modifier.

2019-08-08 14:08 UTC, ANKerD commented on src/test/java/cloud/fogbow/accs/core/ApplicationFacadeTest.java
> +    public void testHandleAuthIssuesWithUnauthorizedUser() throws FogbowException{
Add some space before the curly braces.

2019-08-08 18:38 UTC, wassoares approved these changes

2019-08-09 19:36 UTC, ANKerD approved these changes

2019-08-12 18:58 UTC, merged